# Generated by Django 4.2.11 on 2024-04-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
