# Generated by Django 4.2.11 on 2024-04-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='image_filename',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='data',
            name='video_filename',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
