# Generated by Django 4.2.11 on 2024-04-22 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_data_image_filename_data_video_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('image_filename', models.CharField(default=None, max_length=200)),
                ('img_base64', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('video_filename', models.CharField(default=None, max_length=200)),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
