# Generated by Django 4.2.11 on 2024-04-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_imgdata_videodata_delete_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImgData',
        ),
    ]
