# Generated by Django 4.2.11 on 2024-04-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_delete_imgdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('image_filename', models.CharField(default=None, max_length=200)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
